470PROJECT/class_db/urls.py
  
from django.urls import path, include
from class_db import views
from . import views



urlpatterns = [
    path("", views.home, name="home"),
    path("login", views.user_login, name="login"),
    #path("signup", views.signup, name="signup"),
    #path("schedule", views.schedule, name="schedule"),
    path("information", views.insertRecordProf, name="information"),
    path("schedule", views.insertRecordProfPref, name="schedule"),
    path("about", views.about, name="about"),
    path("logout", views.logout, name="logout"),
    path("register", views.register_request, name="register")
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

470PROJECT/web_project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("class_db.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()

class_db/urls.py
from django.urls import path
from class_db import views
from . import views

app_name = 'scheduling'
urlpatterns = [
    path("", views.home, name="home"),
    path("login", views.login, name="login"),
    #path("signup", views.signup, name="signup"),
    #path("schedule", views.schedule, name="schedule"),
    path("signup", views.insertRecordProf, name="signup"),
    path("schedule", views.insertRecordProfPref, name="schedule")
]

web_project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("class_db.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()

470PROJECT/class_db/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Class(models.Model):
    semester = models.ForeignKey('Semester', models.DO_NOTHING, db_column='Semester', blank=True, null=True)  # Field name made lowercase.
    program = models.CharField(db_column='Program', max_length=10, blank=True, null=True)  # Field name made lowercase.
    cat_num = models.CharField(db_column='Cat_Num', max_length=10, blank=True, null=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=45, blank=True, null=True)  # Field name made lowercase.
    credit_hours = models.DecimalField(db_column='Credit_Hours', max_digits=5, decimal_places=0, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'class'


class Mode(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', unique=True, max_length=45)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'mode'


class PrefType(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    type_name = models.CharField(db_column='Type_Name', unique=True, max_length=45, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'pref_type'


class ProfPreferences(models.Model):
    profid = models.ForeignKey('Professor', models.DO_NOTHING, db_column='ProfID')  # Field name made lowercase.
    pref_type = models.ForeignKey(PrefType, models.DO_NOTHING, db_column='Pref_Type')  # Field name made lowercase.
    start = models.DateTimeField(db_column='Start')  # Field name made lowercase.
    end = models.DateTimeField(db_column='End')  # Field name made lowercase.
    scalar = models.IntegerField(db_column='Scalar', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'prof_preferences'


class ProfSpouse(models.Model):
    id1 = models.OneToOneField('Professor', models.DO_NOTHING, db_column='Id1', primary_key=True)  # Field name made lowercase.
    id2 = models.ForeignKey('Professor', models.DO_NOTHING, db_column='Id2', related_name='+')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'prof_spouse'
        unique_together = (('id1', 'id2'),)


class ProfType(models.Model):
    id = models.IntegerField(primary_key=True)
    type_name = models.CharField(unique=True, max_length=45)
    class_hours = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'prof_type'


class Professor(models.Model):
    fname = models.CharField(db_column='FName', max_length=15, blank=True, null=True)  # Field name made lowercase.
    lname = models.CharField(db_column='LName', max_length=15)  # Field name made lowercase.
    prof_type = models.ForeignKey(ProfType, models.DO_NOTHING, db_column='Prof_Type', blank=True, null=True)  # Field name made lowercase.
    internal_id = models.CharField(db_column='Internal_ID', unique=True, max_length=45, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'professor'


class Room(models.Model):
    building = models.CharField(db_column='Building', max_length=15)  # Field name made lowercase.
    number = models.CharField(db_column='Number', max_length=10)  # Field name made lowercase.
    capacity = models.IntegerField(db_column='Capacity', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'room'


class Section(models.Model):
    section = models.IntegerField(db_column='Section', primary_key=True)  # Field name made lowercase.
    class_field = models.ForeignKey(Class, models.DO_NOTHING, db_column='Class')  # Field name made lowercase. Field renamed because it was a Python reserved word.
    type = models.CharField(db_column='Type', max_length=5, blank=True, null=True)  # Field name made lowercase.
    mode = models.ForeignKey(Mode, models.DO_NOTHING, db_column='Mode', blank=True, null=True)  # Field name made lowercase.
    prof = models.ForeignKey(Professor, models.DO_NOTHING, db_column='Prof_id', blank=True, null=True)  # Field name made lowercase.
    start = models.DateTimeField(db_column='Start', blank=True, null=True)  # Field name made lowercase.
    end = models.DateTimeField(db_column='End', blank=True, null=True)  # Field name made lowercase.
    days = models.CharField(db_column='Days', max_length=7, blank=True, null=True)  # Field name made lowercase.
    room = models.ForeignKey(Room, models.DO_NOTHING, db_column='Room_id', blank=True, null=True)  # Field name made lowercase.
    seats = models.IntegerField(db_column='Seats', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'section'
        unique_together = (('section', 'class_field'),)


class Semester(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    semester_type = models.ForeignKey('SemesterType', models.DO_NOTHING, db_column='Semester_Type', blank=True, null=True)  # Field name made lowercase.
    year = models.TextField(db_column='Year')  # Field name made lowercase. This field type is a guess.

    class Meta:
        managed = False
        db_table = 'semester'


class SemesterType(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=15)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'semester_type'

470PROJECT/class_db/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):

	class Meta:
		model = User
		fields = ("username", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		if commit:
			user.save()
		return user

470PROJECT/class_db/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.http import Http404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from class_db.models import Professor
from class_db.models import ProfPreferences
from class_db.models import ProfType

from .forms import NewUserForm
from django.contrib import messages


def home(request):
    return render(request, "class_db/home.html")

def user_login(request):
    return render(request, "class_db/login.html")

def logout(request):
    return render(request, "accounts/logout")

#def schedule(request):
    #return render(request, "class_db/schedule.html")

def about(request):
    return render(request, "class_db/about.html")

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("class_db/information.html")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="class_db/register.html", context={"register_form":form})

@login_required
def insertRecordProf(request):
    if request.method == 'POST':
        if request.POST.get('fname') and request.POST.get('lname') and request.POST.get('internal_id'):
            saveRecord = Professor()
            saveRecord.fname=request.POST.get('fname')
            saveRecord.lname=request.POST.get('lname')
            saveRecord.internal_id=request.POST.get('internal_id')
            saveRecord.save()
            messages.success(request, 'Record saves successfully')
            return render(request, 'class_db/information.html')
    else:
        return render(request, 'class_db/information.html')

@login_required
def insertRecordProfPref(request):
    results = ProfType.objects.all()
    return render(request, "class_db\schedule.html",{"ProfType":results})
    if request.method == 'POST':
        if request.POST.get('pref_type') and request.POST.get('start') and request.POST.get('end'):
            saveRecord = ProfPreferences()
            saveRecord.pref_type=request.POST.get('pref_type')
            saveRecord.start=request.POST.get('start')
            saveRecord.end=request.POST.get('end')
            saveRecord.save()
            messages.success(request, 'Record saves successfully')
            return render(request, 'class_db\schedule.html')
    else:
        return render(request, 'class_db\schedule.html')
        

class_db/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse

from class_db.models import Professor
from class_db.models import ProfPreferences
from class_db.models import ProfType


from django.contrib import messages


def home(request):
    return render(request, "class_db/home.html")

#def signup(request):
   #return render(request, "class_db/signup.html")

def login(request):
    return render(request, "class_db/login.html")

#def schedule(request):
    #return render(request, "class_db/schedule.html")


def insertRecordProf(request):
    if request.method == 'POST':
        if request.POST.get('fname') and request.POST.get('lname') and request.POST.get('internal_id'):
            saveRecord = Professor()
            saveRecord.fname=request.POST.get('fname')
            saveRecord.lname=request.POST.get('lname')
            saveRecord.internal_id=request.POST.get('internal_id')
            saveRecord.save()
            messages.success(request, 'Record saves successfully')
            return render(request, 'class_db\signup.html')
    else:
        return render(request, 'class_db\signup.html')

def insertRecordProfPref(request):
    results = ProfType.objects.all()
    return render(request, "class_db\schedule.html",{"ProfType":results})
    if request.method == 'POST':
        if request.POST.get('pref_type') and request.POST.get('start') and request.POST.get('end'):
            saveRecord = ProfPreferences()
            saveRecord.pref_type=request.POST.get('pref_type')
            saveRecord.start=request.POST.get('start')
            saveRecord.end=request.POST.get('end')
            saveRecord.save()
            messages.success(request, 'Record saves successfully')
            return render(request, 'class_db\schedule.html')
    else:
        return render(request, 'class_db\schedule.html')
        

class_db/templates/class_db/about.html
{% extends "class_db/layout.html" %}
{% block title %}
abbout
{% endblock %}
{% block content %}
About page :)
{% endblock %}

class_db/templates/class_db/home.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <title>470 Project</title>

    <link rel="stylesheet" href= "{%static 'class_db/site.css'%}"/>
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="left-side">
                <div class="brand">
                    <div>470 Project</div>
                </div>
            </div>

            <div class="right-side">
                <div class="navbar-item active-nav-link">
                    <a href="{% url 'scheduling:home' %}">Home</a>
                </div>
                <div class="navbar-item">
                    <a href="{% url 'scheduling:about'}">About</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:schedule' %}">Schedule</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:login' %}">Login</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:signup' %}">Signup</a>
                </div>

            </div>
        </div>

        <div class="content-wrapper">
            <div class="two-column-wrapper">
                <div class="home-content-wrapper">
                    <h1   style="font-size: 2vw;">Pick the schedule that 
                        is right for you</h1>
                    <form action="{%url 'scheduling:schedule' %}" method="GET">
                    <button>SCHEDULE NOW </button>
                    
                    <p style="font-size: 2vw;">Don't have an account? Sign up <a href= "{%url 'scheduling:signup' %}">here</a></p>
                </div>
            </div>
        </div>
        
    </div>



</html>

class_db/templates/class_db/login.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>470 Project</title>

    <link rel="stylesheet" href= "{%static 'class_db/site.css'%}"/>
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="left-side">
                <div class="brand">
                    <div>470 Project</div>
                </div>
            </div>

            <div class="right-side">
                <div class="navbar-item">
                    <a href="{% url 'scheduling:home' %}">Home</a>
                </div>
                <div class="navbar-item">
                    <a href="{% url 'scheduling:about'}">About</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:schedule' %}">Schedule</a>
                </div>

                <div class="navbar-item active-nav-link">
                    <a href="{%url 'scheduling:login' %}">Login</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:signup' %}">Signup</a>
                </div>
            </div>
        </div>

        <div class="content-wrapper">
            <div class="two-column-wrapper">
                <div class="home-content-wrapper">
                    <h1>
                        Login
                    </h1>
                    <form action="" method="POST">
                   <div>
                       <label for ="email">Email</label>
                       <input type= "email" name="email" id="email">
                   </div>

                    <div>
                        <label for ="password">Password</label>
                        <input type= "password" name="password" id="password">
                    </div>
                    <button type = "submit">Login</button>
                    <p>Don't have an account? Join <a href= "{%url 'scheduling:signup' %}">here</a></p>
                    
                </div>
            </div>
        </div>
        
    </div>



</html>

class_db/templates/class_db/schedule.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>470 Project</title>
    <link rel="stylesheet" href= "{%static 'class_db/site.css'%}"/>
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="left-side">
                <div class="brand">
                    <div>470 Project</div>
                </div>
            </div>

            <div class="right-side">
                <div class="navbar-item">
                    <a href="{% url 'scheduling:home' %}">Home</a>
                </div>
                <div class="navbar-item">
                    <a href="{% url 'scheduling:about'}">About</a>
                </div>

                <div class="navbar-item active-nav-link">
                    <a href="{%url 'scheduling:schedule' %}">Schedule</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:login' %}">Login</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:signup' %}">Signup</a>
                </div>
            </div>
        </div>

        <div class="content-wrapper">
            <div class="two-column-wrapper">
                <div class="home-content-wrapper">
                    <h1>
                        Schedule Information
                    </h1>
                    <form method="POST"> {% csrf_token %}
                        <!--
                            <div>
                            <label for="tenure">Tenure Track</label>
                            <select name="tenure" id="tenure">
                                <option value="tenure">Tenure</option>
                                <option value="tenure">1 year</option>
                                <option value="tenure">2 years</option>
                                <option value="tenure">3 years</option>
                                <option value="tenure">4 years</option>
                                <option value="tenure">5 years</option>
                            </select>
                        </div>

                        <div>
                            <label for="salary">Salary</label>
                            <select name="salary" id="salary">
                                <option value="salary">Salary</option>
                                <option value="salary">$35,000-$40,000</option>
                                <option value="salary">$45,000-$50,000</option>
                                <option value="salary">$55,000-$60,000</option>
                                <option value="salary">$65,000-$70,000</option>
                                <option value="salary">$75,000</option>
                            </select>
                        </div>

                        <div>
                            <label for="schedule">Scheduling Preferences</label>
                            <select name="schedule" id="schedule">
                                <option value="Day">Day</option>
                                <option value="Monday">Monday</option>
                                <option value="Tuesday">Tuesday</option>
                                <option value="Wendesday">Wendesday</option>
                                <option value="Thursday">Thursday</option>
                                <option value="Friday">Friday</option>
                            </select>
                        -->
                        <div>
                            <label for="profType">Preference Type</label>
                            <select name="ProfType">
                                <option disabled='true' selected>-- Select Preference --</option>
                                {% for results in ProfType%}
                                <option>{{results.id}}.  {{results.type_name}}</option>
                                {% endfor%}
                                <!--
                                <option value="Type 1">TT/T</option>
                                <option value="Type 2">FTA</option>
                                <option value="Type 3">PTA</option>
                                <option value="Type 4">GTA</option>
                                -->
                            </select>

                        </div>
                        <div>

                            <label for ="Start">Start Time</label>
                            <input type="time" name="start" id="Start"><br/>
                            <label for ="End">End Time</label>
                            <input type="time" name="end" id="End">

                        </div>

                        <button type = "submit">Schedule Now</button>
                        {% if messages%}
                        {% for message in messages %}
                        <h2 style="color: green;">{{message}}</h2>
                        {%endfor%}
                        {% endif %}
                    </form>
                        

                    <p>Already have an account? Log in <a href= "{%url 'scheduling:login' %}">here</a></p>
                    
                </div>
            </div>
        </div>
        
    </div>



</html>

class_db/templates/class_db/signup.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>470 Project</title>
    <link rel="stylesheet" href= "{%static 'class_db/site.css'%}"/>
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="left-side">
                <div class="brand">
                    <div>470 Project</div>
                </div>
            </div>

            <div class="right-side">
                <div class="navbar-item">
                    <a href="{% url 'scheduling:home' %}">Home</a>
                </div>
                <div class="navbar-item">
                    <a href="{% url 'scheduling:about'}">About</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:schedule' %}">Schedule</a>
                </div>

                <div class="navbar-item">
                    <a href="{%url 'scheduling:login' %}">Login</a>
                </div>

                <div class="navbar-item active-nav-link">
                    <a href="{%url 'scheduling:signup' %}">Signup</a>
                </div>
            </div>
        </div>

        <div class="content-wrapper">
            <div class="two-column-wrapper">
                <div class="home-content-wrapper">
                    <h1>
                        Join
                    </h1>
                    <form method="POST">{% csrf_token %}
                    <label for ="name">Name</label><br/>
                    <input type= "text" name="fname" id="name" placeholder="First"><br/>
                    <input type= "text" name="lname" id="name" placeholder="Last" required><br/>
                   <!--
                    <div>
                    <label for ="email">Email</label>
                    <input type= "email" name="email" id="email">
                    <div>
                        <label for ="DOB">Date of birth</label>
                        <select name="DOB" id="DOB">
                            <option value="Month">Month</option>
                            <option value="Month">01</option>
                            <option value="Month">02</option>
                            <option value="Month">03</option>
                            <option value="Month">04</option>
                            <option value="Month">05</option>
                            <option value="Month">06</option>
                            <option value="Month">07</option>
                            <option value="Month">08</option>
                            <option value="Month">09</option>
                            <option value="Month">10</option>
                            <option value="Month">11</option>
                            <option value="Month">12</option>
                        </select>
                        <select name="DOB" id="DOB">
                            <option value="Day">Day</option>
                            <option value="Day">01</option>
                            <option value="Day">02</option>
                            <option value="Day">03</option>
                            <option value="Day">04</option>
                            <option value="Day">05</option>
                            <option value="Day">06</option>
                            <option value="Day">07</option>
                            <option value="Day">08</option>
                            <option value="Day">09</option>
                            <option value="Day">10</option>
                            <option value="Day">11</option>
                            <option value="Day">12</option>
                            <option value="Day">13</option>
                            <option value="Day">14</option>
                            <option value="Day">15</option>
                            <option value="Day">16</option>
                            <option value="Day">17</option>
                            <option value="Day">18</option>
                            <option value="Day">19</option>
                            <option value="Day">20</option>
                            <option value="Day">21</option>
                            <option value="Day">22</option>
                            <option value="Day">23</option>
                            <option value="Day">24</option>
                            <option value="Day">25</option>
                            <option value="Day">26</option>
                            <option value="Day">27</option>
                            <option value="Day">28</option>
                            <option value="Day">29</option>
                            <option value="Day">30</option>
                            <option value="Day">31</option>
                        </select>
                        <select name="DOB" id="DOB">
                            <option value="year">Year</option>
                            <option value="year">1970</option>
                            <option value="year">1971</option>
                            <option value="year">1972</option>
                            <option value="year">1973</option>
                            <option value="year">1974</option>
                            <option value="year">1975</option>
                            <option value="year">1976</option>
                            <option value="year">1977</option>
                            <option value="year">1978</option>
                            <option value="year">1979</option>
                            <option value="year">1980</option>
                            <option value="year">1981</option>
                            <option value="year">1982</option>
                            <option value="year">1983</option>
                            <option value="year">1984</option>
                            <option value="year">1985</option>
                            <option value="year">1986</option>
                            <option value="year">1987</option>
                            <option value="year">1988</option>
                            <option value="year">1989</option>
                            <option value="year">1990</option>
                            <option value="year">1991</option>
                            <option value="year">1992</option>
                            <option value="year">1993</option>
                            <option value="year">1994</option>
                            <option value="year">1995</option>
                            <option value="year">1996</option>
                            <option value="year">1997</option>
                            <option value="year">1998</option>
                            <option value="year">1999</option>
                            <option value="year">2000</option>
                        </select>
                    </div>
                    <div>
                   -->
                   
                    <!--<label for ="sex">Sex</label>
                        <select name="sex" id="sex">
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>
                    -->
                    <div>
                        <label for ="id">ID Number</label>
                        <input type= "text" name="internal_id" id="id" placeholder="(ex. 124467)">
                    </div>
                    <!--
                    <div>
                        <label for ="username">Username</label>
                        <input type= "text" name="username" id="username">
                    </div>
                    <div>
                        <label for ="password">Password</label>
                        <input type= "password" name="password" id="password">
                    </div>

                    -->
                    
                    <button type = "submit">Join</button>
                    {% if messages%}
                    {% for message in messages %}
                        <h2 style="color: blue;">{{message}}</h2>
                    {%endfor%}
                    {% endif %}
                    </form>

                    <p>Already have an account? Log in <a href= "{%url 'scheduling:login' %}">here</a></p>
                    
                </div>
            </div>
        </div>
        
    </div>



</html>